// Code generated by "stringer -type=AudioStatus"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AUDIO_STOPPED-0]
	_ = x[AUDIO_PLAYING-1]
	_ = x[AUDIO_PAUSED-2]
}

const _AudioStatus_name = "AUDIO_STOPPEDAUDIO_PLAYINGAUDIO_PAUSED"

var _AudioStatus_index = [...]uint8{0, 13, 26, 38}

func (i AudioStatus) String() string {
	if i >= AudioStatus(len(_AudioStatus_index)-1) {
		return "AudioStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AudioStatus_name[_AudioStatus_index[i]:_AudioStatus_index[i+1]]
}
