// Code generated by "stringer -type=AudioFormat"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AUDIO_S8-32776]
	_ = x[AUDIO_U8-8]
	_ = x[AUDIO_S16LSB-32784]
	_ = x[AUDIO_S16MSB-36880]
	_ = x[AUDIO_S16SYS-32784]
	_ = x[AUDIO_S16-32784]
	_ = x[AUDIO_U16LSB-16]
	_ = x[AUDIO_U16MSB-4112]
	_ = x[AUDIO_U16SYS-16]
	_ = x[AUDIO_U16-16]
	_ = x[AUDIO_S32LSB-32800]
	_ = x[AUDIO_S32MSB-36896]
	_ = x[AUDIO_S32SYS-32800]
	_ = x[AUDIO_S32-32800]
	_ = x[AUDIO_F32LSB-33056]
	_ = x[AUDIO_F32MSB-37152]
	_ = x[AUDIO_F32SYS-33056]
	_ = x[AUDIO_F32-33056]
}

const (
	_AudioFormat_name_0 = "AUDIO_U8"
	_AudioFormat_name_1 = "AUDIO_U16LSB"
	_AudioFormat_name_2 = "AUDIO_U16MSB"
	_AudioFormat_name_3 = "AUDIO_S8"
	_AudioFormat_name_4 = "AUDIO_S16LSB"
	_AudioFormat_name_5 = "AUDIO_S32LSB"
	_AudioFormat_name_6 = "AUDIO_F32LSB"
	_AudioFormat_name_7 = "AUDIO_S16MSB"
	_AudioFormat_name_8 = "AUDIO_S32MSB"
	_AudioFormat_name_9 = "AUDIO_F32MSB"
)

func (i AudioFormat) String() string {
	switch {
	case i == 8:
		return _AudioFormat_name_0
	case i == 16:
		return _AudioFormat_name_1
	case i == 4112:
		return _AudioFormat_name_2
	case i == 32776:
		return _AudioFormat_name_3
	case i == 32784:
		return _AudioFormat_name_4
	case i == 32800:
		return _AudioFormat_name_5
	case i == 33056:
		return _AudioFormat_name_6
	case i == 36880:
		return _AudioFormat_name_7
	case i == 36896:
		return _AudioFormat_name_8
	case i == 37152:
		return _AudioFormat_name_9
	default:
		return "AudioFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
