// Code generated by "stringer -type=ErrorCode"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ENOMEM-0]
	_ = x[EFREAD-1]
	_ = x[EFWRITE-2]
	_ = x[EFSEEK-3]
	_ = x[UNSUPPORTED-4]
	_ = x[LASTERROR-5]
}

const _ErrorCode_name = "ENOMEMEFREADEFWRITEEFSEEKUNSUPPORTEDLASTERROR"

var _ErrorCode_index = [...]uint8{0, 6, 12, 19, 25, 36, 45}

func (i ErrorCode) String() string {
	if i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
