// Code generated by "stringer -type=FlashOperation"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FLASH_CANCEL-0]
	_ = x[FLASH_BRIEFLY-1]
	_ = x[FLASH_UNTIL_FOCUSED-2]
}

const _FlashOperation_name = "FLASH_CANCELFLASH_BRIEFLYFLASH_UNTIL_FOCUSED"

var _FlashOperation_index = [...]uint8{0, 12, 25, 44}

func (i FlashOperation) String() string {
	if i >= FlashOperation(len(_FlashOperation_index)-1) {
		return "FlashOperation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FlashOperation_name[_FlashOperation_index[i]:_FlashOperation_index[i+1]]
}
