// Code generated by "stringer -type=GameControllerType"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CONTROLLER_TYPE_UNKNOWN-0]
	_ = x[CONTROLLER_TYPE_XBOX360-1]
	_ = x[CONTROLLER_TYPE_XBOXONE-2]
	_ = x[CONTROLLER_TYPE_PS3-3]
	_ = x[CONTROLLER_TYPE_PS4-4]
	_ = x[CONTROLLER_TYPE_NINTENDO_SWITCH_PRO-5]
	_ = x[CONTROLLER_TYPE_VIRTUAL-6]
	_ = x[CONTROLLER_TYPE_PS5-7]
}

const _GameControllerType_name = "CONTROLLER_TYPE_UNKNOWNCONTROLLER_TYPE_XBOX360CONTROLLER_TYPE_XBOXONECONTROLLER_TYPE_PS3CONTROLLER_TYPE_PS4CONTROLLER_TYPE_NINTENDO_SWITCH_PROCONTROLLER_TYPE_VIRTUALCONTROLLER_TYPE_PS5"

var _GameControllerType_index = [...]uint8{0, 23, 46, 69, 88, 107, 142, 165, 184}

func (i GameControllerType) String() string {
	if i >= GameControllerType(len(_GameControllerType_index)-1) {
		return "GameControllerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameControllerType_name[_GameControllerType_index[i]:_GameControllerType_index[i+1]]
}
