// Code generated by "stringer -type=SensorType"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SENSOR_INVALID - -1]
	_ = x[SENSOR_UNKNOWN-0]
	_ = x[SENSOR_ACCEL-1]
	_ = x[SENSOR_GYRO-2]
}

const _SensorType_name = "SENSOR_INVALIDSENSOR_UNKNOWNSENSOR_ACCELSENSOR_GYRO"

var _SensorType_index = [...]uint8{0, 14, 28, 40, 51}

func (i SensorType) String() string {
	i -= -1
	if i < 0 || i >= SensorType(len(_SensorType_index)-1) {
		return "SensorType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _SensorType_name[_SensorType_index[i]:_SensorType_index[i+1]]
}
