// Code generated by "stringer -type=TouchDeviceType"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TOUCH_DEVICE_INVALID - -1]
	_ = x[TOUCH_DEVICE_DIRECT-0]
	_ = x[TOUCH_DEVICE_INDIRECT_ABSOLUTE-1]
	_ = x[TOUCH_DEVICE_INDIRECT_RELATIVE-2]
}

const _TouchDeviceType_name = "TOUCH_DEVICE_INVALIDTOUCH_DEVICE_DIRECTTOUCH_DEVICE_INDIRECT_ABSOLUTETOUCH_DEVICE_INDIRECT_RELATIVE"

var _TouchDeviceType_index = [...]uint8{0, 20, 39, 69, 99}

func (i TouchDeviceType) String() string {
	i -= -1
	if i < 0 || i >= TouchDeviceType(len(_TouchDeviceType_index)-1) {
		return "TouchDeviceType(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _TouchDeviceType_name[_TouchDeviceType_index[i]:_TouchDeviceType_index[i+1]]
}
