// Code generated by "stringer -type=YUV_CONVERSION_MODE"; DO NOT EDIT.

package sdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[YUV_CONVERSION_JPEG-0]
	_ = x[YUV_CONVERSION_BT601-1]
	_ = x[YUV_CONVERSION_BT709-2]
	_ = x[YUV_CONVERSION_AUTOMATIC-3]
}

const _YUV_CONVERSION_MODE_name = "YUV_CONVERSION_JPEGYUV_CONVERSION_BT601YUV_CONVERSION_BT709YUV_CONVERSION_AUTOMATIC"

var _YUV_CONVERSION_MODE_index = [...]uint8{0, 19, 39, 59, 83}

func (i YUV_CONVERSION_MODE) String() string {
	if i >= YUV_CONVERSION_MODE(len(_YUV_CONVERSION_MODE_index)-1) {
		return "YUV_CONVERSION_MODE(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _YUV_CONVERSION_MODE_name[_YUV_CONVERSION_MODE_index[i]:_YUV_CONVERSION_MODE_index[i+1]]
}
